services:
  - type: web
    name: plumbing-supplies-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true

  - type: static
    name: plumbing-supplies-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://plumbing-supplies-api.onrender.com
    autoDeploy: true
